version: "3.9"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5005:80"
    networks:
      - frontend


  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5006:80"
      - "5858:5858"
    networks:
      - backend
     

  worker:
    build:
      context: ./worker
    networks:
      - backend
      - frontend

  redis:
    image: redis:5.0-alpine3.10
    ports: ["6379"]
    networks:
      - frontend

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
